server:
  port: 8080
spring:
  application:
    name: customer
  datasource:
    username: 'postgres'
    password: 'password'
    url: jdbc:postgresql://localhost:5432/userservice
  jpa:
    database-platform: postgres
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true